### ISSUE TITLE
CSS color marked as tags.

### ISSUE THREAD

**Issue by coke** [RapidApp/tpf-blog-live#1]
/list?tag=1155cc

Shows 10 hits, which appear to be CSS color styling. (the tag doesn't appear in the text of the article, but in the raw HTML source)

**Comment by vanstyn** [comment]
Mmmm.... right, so, the way the Tags in Rapi::Blog work is by automatically parsing the body and looking for hashtag style keywords. I didn't anticipate the case of inline CSS within the body and hex colors. So, in order to fix this, the more complicated solution would be to try to detect context and being within style tags, but that could open a nasty can of worms ... the easier solution might be to just ignore hashtags which look like hex. This is what I already did for numeral-only hashtags, I could just expand this to also exclude hex-only. There are only a handful of words that could overlap, like fed .... maybe I could be more picky when excluding letter only hex. thoughts?

**Comment by coke** [comment]
Ignoring hex codes seems fine to me. Maybe only ignore 6 digit hex?

**Comment by coke** [comment]
(or any size that includes numerics?)

**Comment by vanstyn** [comment]
Yeah I thought 6 digit too, but then I thought about fff. And, yeah, any length hex that contains numbers, all letter-only hex 6 characters or longer, and a few custom cases like fff. Or, maybe make the custom cases actual words, and exclude all hex-only values of any length, unless they are one of a list of known words

**Comment by coke** [comment]
how about all 3/6 digit valid hex, and if it's a problem, we can whitelist later?

**Comment by vanstyn** [comment]
This has now been fixed as of Rapi::Blog v1.400. Hex-looking 3 or 6 length tags are ignored. I did not add an exclusion for words (just didn't have enough time, too much stuff on my plate), so if people want to tag things with 'fed' they'll just be out of luck.

I also manually deleted the 1155cc tag which had already been created
