### ISSUE TITLE
Can't create an account (names should be unique?)

### ISSUE THREAD

**Issue by AlexDaniel** [RapidApp/tpf-blog-live#14]
Now it's no longer possible to leave comments without an account, so I'm trying to make one.

However, when I try it, it says `Supplied Full Name is already in use`, as if people's names are unique:

![image](https://user-images.githubusercontent.com/5507503/79765562-7356ee80-832f-11ea-9957-32c596718dff.png)

FWIW I was also unable to use `Forgot Password` and `E-Mail Login` features. It's possible that I used a different email but I can't know which one.

@coke

**Comment by coke** [comment]
bump. Any update on this ticket?

**Comment by AlexDaniel** [comment]
@coke it is still giving exactly the same error.

**Comment by vanstyn** [comment]
"as if people's names are unique" <-- yes, they are! Well, at least we assume they are for the purposes of this system, since with a user pool so small, a duplicate full-name is more likely to be a duplicate user. This was a design decision which was considered and made. And, in this particular case, that seems to be the case. The already registered E-Mail address contains the string 'perl6' if that helps (not posting a real e-mail address here for courtesy/safety).

So, this is not a bug. The system is working as designed. This should be an admin request, not a bug report. That said, if everyone truly thinks it is better to allow duplicate full-names, then this could be changed. I personally don't agree. I think it is better this way. Neither choice can be perfect, but we don't want multiple/dead accounts piling up in the system. That is the rationale, and frankly is worked as intended here.

**Comment by AlexDaniel** [comment]
@vanstyn good point! Yeah, turns out there was an account already. Anyway, thanks for mentioning the right email address :)

Yeah, names being unique is wrong in principle but for a small system it can be ignored for practicality.

Thank you!

**Comment by vanstyn** [comment]
@AlexDaniel - I'm willing to bet you're the only Aleks-Daniel Jakimenko-Aleksejev on the planet ;P
