### ISSUE TITLE
no way to format comments?

### ISSUE THREAD

**Issue by karenetheridge** [RapidApp/tpf-blog-live#15]
It looks like double line breaks are insufficient to separate paragaphs when submitting comments. How is the formatting done? Can a formatting guide be linked from each page?

**Comment by coke** [comment]
❌ !!

Tested some things out on a very old post. The secret... is to use raw HTML. And there is no cleansing being done, so it's possible for users to inject javascript into the site. This is a very big issue and needs to be addressed.

**Comment by vanstyn** [comment]
Agreed javascript injection is a big issue. This is something that I thought was already sanitized but clearly not (thanks @coke for the offline demonstration). I apologize for the slow response on some of these issues. I have been incredibly swamped; basically since the start of the covid stuff. But this is something that can't wait. I will address as well as other open issues within a couple days

**Comment by vanstyn** [comment]
The Javascript injection vulnerability has now been addressed with Rapi::Blog v1.400 which has now been deployed on the live TPF blog site. Comments are sanitized using HTML::Scrubber to remove all dangerous content tags like script, style, iframe and so on, but HTML is still allowed.

Additionally, comments with newlines but no html tags have those newlines converted to br tags when rendered, but if any HTML tags are used, it is rendered as-is (after being sanitized). This was the best compromise based on looking at many of the comments already in the system. It appears many people have already been using html, and for those not, the newline clobbering seems to be the most unexpected and problematic result.
