### ISSUE TITLE
https redirect

### ISSUE THREAD

**Issue by coke** [RapidApp/tpf-blog-live#2]
Logged in today, happened to have gone through the http site, so got a browser warning.

We should at least force HTTPS on login, but there's a case to be made to redirect any hits to HTTP to their HTTPS alternate.

**Comment by vanstyn** [comment]
Right, so, the old site wasn't https ..... unless it was and I just didn't realize because it didn't automatically redirect to https, as I sort of assume these days. I don't have an SSL certificate for news.perfoundation.org, but this was already something I had planned to handle after go live. I'll try to get this done sooner than later

**Comment by vanstyn** [comment]
This is now the case, and has been for the past week or so. I hesitated because i was worried about some of the sites pulling from the feed (I just learned about some other sites which pull TPF posts via automated process. But everything seems to be working so I think we're good
