### ISSUE TITLE
Everything Crashes After Changing Username

### ISSUE THREAD

**Issue by wbraswell** [RapidApp/tpf-blog-live#6]
I used the "e-mail login" link as directed, logged in, and the first thing I did was change my username from "williamn_braswell_jr" to "wbraswell".

Then I tried to view my 1 pre-authorization, which immediately crashed (see image).
![perlfoundation_20191004-rapiblog_preauth_error](https://user-images.githubusercontent.com/1772630/66249499-33654c80-e6fa-11e9-800c-92bdbcd3f398.png)

Then I tried to change my username back, which also crashed (see image).
![perlfoundation_20191004-rapiblog_username_error](https://user-images.githubusercontent.com/1772630/66249505-3b24f100-e6fa-11e9-8fce-a15c3e84a3f7.png)

Then I tried to change my password, which also crashed (see image).
![perlfoundation_20191004-rapiblog_password_error](https://user-images.githubusercontent.com/1772630/66249506-3f510e80-e6fa-11e9-9b02-ed140b6bacb2.png)

Then I tried to simply view the "Details of the new TPF blog site" post, which also crashed (see image).
![perlfoundation_20191004-rapiblog_view_error](https://user-images.githubusercontent.com/1772630/66249508-4415c280-e6fa-11e9-86e3-03c31bac1a4a.png)

Fortunately, I was able to click the "home" button, then the "sign out" button, then do the "e-mail login" again, at which point I saw the new username "wbraswell" displayed, and I was able to carry on without any crashes, including setting my new password and writing a comment on the blog post.

**Comment by vanstyn** [comment]
The way the error messages rendered needs to be improved, but it looks like the core/start of problem was just that you tried to change your username to a username which was already taken. You shouldn't have needed to "change it back" because the error indicated that the change was denied ... Obviously more went wrong from there. I'll investigate the sequence you reported to figure out where the bug is.

Thank you for the detailed report! Now I actually have something useful to be able to investigate and probably be able to figure it out

**Comment by vanstyn** [comment]
And, just to confirm, your account is now back to being fully functional, this is just a report for me to be able to fix whatever happened to make sure it doesn't happen again, right? Just want to make sure you're not stuck on anything...

**Comment by vanstyn** [comment]
Actually, scratch my first comment. I didn't realize at first what the first screencap was... I'm sure that the bug is that the session needs to be updated during the username change, and I don't believe that is happening now, and it certainly needs to. Thanks again for the feedback.

**Comment by wbraswell** [comment]
To answer in the order of your comments...
No, I was not trying to choose a username which was already taken.  I went from "williamn_braswell_jr" to "wbraswell", neither of which was taken.  I am now currently using "wbraswell" successfully.
...
Yes my account seems to be working correctly now.
...
Yes I think the bug is related to the session needing to be updated to the new username.  You may want to consider NOT allowing people to just change their usernames so easily.  I'm glad I was able to do it, but I can think of lots of reasons why I would not want people randomly changing their usernames if I were the admin.

**Comment by vanstyn** [comment]
I want to allow people to do it, since the site has only been up for two days and several people have expressed interest (you're the first user it blew up on)

I'm going to try to be really clever about it and actually manipulate the active session and make it "just work" .... or, an easier solution would be to just force them to logout after changing it (with a prompt and the chance for them to decide not to proceed, of course)

**Comment by vanstyn** [comment]
This is fixed and is live now. Maximum overkill: https://github.com/vanstyn/RapidApp/commit/79aac1784072
